services:
  database:
    image: mysql:8.1
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: opencart
      MYSQL_USER: opencart
      MYSQL_PASSWORD: opencart123
      MYSQL_ROOT_PASSWORD: root123
    restart: always
    volumes:
      - database_data:/var/lib/mysql

  opencart:
    build: .
    restart: always
    ports:
      - "8081:80"
    volumes:
      - opencart_data:/var/www/html
      - ./lodin/upload:/var/www/html/extension/lodin
      - ./lodin/image/lodin:/var/www/html/image/lodin
    depends_on:
      - database

volumes:
  database_data:
  opencart_data: